apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  containers:
  - image: andersonlando/reverseproxy
    name: reverseproxy
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
  restartPolicy: Always