apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverseproxy
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
        service: reverseproxy
    spec:
      containers:
      - image: andersonlando/reverseproxy
        name: reverseproxy
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always


